INSERT INTO reviews (content, star_rating, reviewer_id, dish_id)
VALUES
('This food was amazing! Will try again', 5, 1, 1),
('This food was awful! Who would even eat this?', 1, 2, 1),
('This food was okay. Maybe I would try it again.', 3, 3, 2),
('Yee haw! This could feed my horse!', 5, 1, 2),
('I really liked this!', 4, 2, 3),
('I could not eat this!', 2, 3, 3),
('I had high hopes for this place. The menu didnt match the one on their website.', 2, 3, 3),
('Yumm-o! The food was cooked to perfection. Try out the huge selection of incredible appetizers.', 5, 3, 3),
('Decent place. Try out the huge selection of incredible appetizers. Everything was just so yummy.', 4, 3, 3),
('This was a pretty good dish! Would try again', 3, 4, 4),
('It was good but it was way too spicy for me!', 3, 5, 5),
('Super good, just what I needed!', 5, 5, 5),
('Worst thing I have ever eaten! Still giving it 5 stars tho', 5, 6, 6),
('Large portions for the price, but the food was meh!', 3, 7, 7),
('Nope, not for me', 1, 8, 8),
('Was just what I was looking for on the way home from a night out!', 5, 8, 8),
('I cannot believe I liked this, I usually am really picky!', 4, 9, 9),
('Amazing food, I would recommend it to anyone', 5, 10, 10),
('Might come back if I was forced to', 2, 11, 10);
